name: graphql permissions test

on:
  workflow_dispatch:

jobs:
  api_test:
    runs-on: ubuntu-latest
    steps:
      - name: graphql api test
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            const response = await github.rest.pulls.get({
              owner: 'testing-ground-1',
              repo: 'test-inventory',
              pull_number: '1',
            });


            // Enable Auto Merge
            await github.graphql({
              query: `
                mutation($pullRequestId: ID!) {
                  enablePullRequestAutoMerge(input: {pullRequestId: $pullRequestId, mergeMethod: MERGE}) {
                    pullRequest {
                      autoMergeRequest {
                        enabledAt
                      }
                    }
                  }
                }
              `,
              pullRequestId: response.node_id
            });
